[build]
  publish = "public"
  command = "make"

[[redirects]]
  from = "/"
  to = "/noindex.html"
  query = {repo = ":repo"}
  status = 200
  force = false

[[redirects]]
  from = "/:module"
  to = "/noindex.html"
  status = 200
  force = false
